name: Code Quality

on:
  pull_request:

permissions:
  contents: read
  pull-requests: write

concurrency:
  group: code-quality-${{ github.ref }}
  cancel-in-progress: true

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      - uses: ./.github/actions/ci-setup
      - run: go mod download
      - run: golangci-lint run --timeout=10m

  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      - uses: ./.github/actions/ci-setup
      - run: go mod download
      - name: Run tests
        run: |
          gotestsum --junitfile unit-tests.xml --format pkgname \
            -- -tags test -timeout 5m -coverpkg=./... -coverprofile=cover.out ./...
      - uses: test-summary/action@37b508cfee6d4d080eedd00b5bb240a6a784a6a5 # v2.6
        with:
          paths: "unit-tests.xml"
        if: always()
