name: Code Quality

on:
  pull_request:

permissions:
  contents: read
  pull-requests: write

concurrency:
  group: code-quality-${{ github.ref }}
  cancel-in-progress: true

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      - uses: actions/setup-go@4b73464bb391d4059bd26b0524d20df3927bd417 # v6.3.0
        with:
          go-version-file: go.mod
          cache-dependency-path: go.sum
      - run: go mod download
      - uses: golangci/golangci-lint-action@1e7e51e771db61008b38414a730f564565cf7c20 # v9.2.0
        with:
          args: --timeout=10m
  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      - uses: actions/setup-go@4b73464bb391d4059bd26b0524d20df3927bd417 # v6.3.0
        with:
          go-version-file: go.mod
          cache-dependency-path: go.sum
      - run: go mod download
      - run: go run gotest.tools/gotestsum@latest --junitfile unit-tests.xml --format pkgname -- -tags test -coverpkg=./... -coverprofile=cover.out ./...
      - uses: test-summary/action@31493c76ec9e7aa675f1585d3ed6f1da69269a86  # v2.4.0
        with:
          paths: "unit-tests.xml"
        if: always()
